name: CMake Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-all:
    name: |
      ${{ matrix.os.env }} - ${{ matrix.compiler }} - ${{ matrix.build_type }} - ${{ matrix.lib_config.type }}
    runs-on: ${{ matrix.os.label }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - { env: "Linux-x64", label: "ubuntu-latest" }
          - { env: "Windows-x64", label: "windows-latest" }
        compiler: [gcc, clang, clang-cl, msvc]
        build_type: [Release, Debug]
        lib_config:
          - { type: "shared", flag: "ON" }
          - { type: "static", flag: "OFF" }
        exclude:
          - os: { env: "Linux-x64", label: "ubuntu-latest" }
            compiler: clang-cl
          - os: { env: "Linux-x64", label: "ubuntu-latest" }
            compiler: msvc

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Setup Windows Env
        if: matrix.os.env == 'Windows-x64'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Set Compiler Env
        shell: bash
        run: |
          if [ "${{ matrix.compiler }}" == "gcc" ]; then
            echo "CC=gcc" >> $GITHUB_ENV
            echo "CXX=g++" >> $GITHUB_ENV
          elif [ "${{ matrix.compiler }}" == "clang" ]; then
            echo "CC=clang" >> $GITHUB_ENV
            echo "CXX=clang++" >> $GITHUB_ENV
          elif [ "${{ matrix.compiler }}" == "clang-cl" ]; then
            echo "CC=clang-cl" >> $GITHUB_ENV
            echo "CXX=clang-cl" >> $GITHUB_ENV
          elif [ "${{ matrix.compiler }}" == "msvc" ]; then
            echo "CC=cl" >> $GITHUB_ENV
            echo "CXX=cl" >> $GITHUB_ENV
          fi

      - name: Configure
        shell: bash
        run: |
          cmake \
            -S . \
            -B build \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DBUILD_SHARED_LIBS=${{ matrix.lib_config.flag }} \
            \
            -DSIRIUS_TEST_ENABLE=ON

      - name: Compile
        run: cmake --build build

      - name: Run Tests
        working-directory: .
        run: ctest --test-dir build -j4 --output-on-failure --timeout 600

  build-options-linux:
    name: |
      Linux-x64 - OBJECT:${{ matrix.build_object_only }} - PIC:${{ matrix.pic_enable }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - build_object_only: OFF
            pic_enable: OFF
          - build_object_only: ON
            pic_enable: ON

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure
        shell: bash
        run: |
          cmake \
            -S . \
            -B build \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_CXX_COMPILER=clang++ \
            -DBUILD_SHARED_LIBS=ON \
            -DSIRIUS_BUILD_OBJECT_ONLY=${{ matrix.build_object_only }} \
            \
            -DSIRIUS_PIC_ENABLE=${{ matrix.pic_enable }} \
            \
            -DSIRIUS_TEST_ENABLE=ON \
            -DSIRIUS_TEST_PIE_ENABLE=ON

      - name: Compile
        run: cmake --build build --parallel 4

      - name: Run Tests
        working-directory: .
        run: ctest --test-dir build -j4 --output-on-failure --timeout 600

  build-options-windows:
    name: Windows-x64 - OBJECT:ON
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Windows Env
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure
        run: cmake -S . -B build -DSIRIUS_BUILD_OBJECT_ONLY=ON -DSIRIUS_TEST_ENABLE=ON

      - name: Compile
        run: cmake --build build --config Release --parallel 4

      - name: Run Tests
        working-directory: .
        run: ctest --test-dir build -C Release -j4 --output-on-failure --timeout 600
