name: Meson Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-all:
    name: |
      ${{ matrix.os.env }} - ${{ matrix.compiler }} - ${{ matrix.build_type }} - ${{ matrix.lib_type }}
    runs-on: ${{ matrix.os.label }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - { env: "Linux-x64", label: "ubuntu-latest" }
          - { env: "Windows-x64", label: "windows-latest" }
        compiler: [gcc, clang, clang-cl, msvc]
        build_type: [release, debug]
        lib_type: [shared, static]
        exclude:
          - os: { env: "Linux-x64", label: "ubuntu-latest" }
            compiler: clang-cl
          - os: { env: "Linux-x64", label: "ubuntu-latest" }
            compiler: msvc

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install Meson & Ninja
        run: pip install meson ninja

      - name: Setup Windows Env
        if: matrix.os.env == 'Windows-x64'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Set Compiler Env
        shell: bash
        run: |
          if [ "${{ matrix.compiler }}" == "gcc" ]; then
            echo "CC=gcc" >> $GITHUB_ENV
            echo "CXX=g++" >> $GITHUB_ENV
          elif [ "${{ matrix.compiler }}" == "clang" ]; then
            echo "CC=clang" >> $GITHUB_ENV
            echo "CXX=clang++" >> $GITHUB_ENV
          elif [ "${{ matrix.compiler }}" == "clang-cl" ]; then
            echo "CC=clang-cl" >> $GITHUB_ENV
            echo "CXX=clang-cl" >> $GITHUB_ENV
          elif [ "${{ matrix.compiler }}" == "msvc" ]; then
            # Simple and brutal methods always work.
            mv "C:/Program Files/Git/usr/bin/link.exe" "C:/Program Files/Git/usr/bin/link.exe.bak" || true

            echo "CC=cl" >> $GITHUB_ENV
            echo "CXX=cl" >> $GITHUB_ENV
          fi

      - name: Configure
        shell: bash
        run: |
          meson \
            setup builddir \
            --vsenv \
            -Dbuildtype=${{ matrix.build_type }} \
            -Ddefault_library=${{ matrix.lib_type }} \
            \
            -Dtest-enable=true

      - name: Compile
        run: meson compile -C builddir

      - name: Run Tests
        working-directory: .
        run: meson test -C builddir --num-processes 4 --print-errorlogs

  build-options-linux:
    name: Linux-x64 - OBJECT:${{ matrix.build_object_only }} - PIC:${{ matrix.pic_enable }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - build_object_only: false
            pic_enable: false
          - build_object_only: true
            pic_enable: true

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install Meson & Ninja
        run: pip install meson ninja

      - name: Set Compiler Env
        shell: bash
        run: |
          echo "CC=clang" >> $GITHUB_ENV
          echo "CXX=clang++" >> $GITHUB_ENV

      - name: Configure
        shell: bash
        run: |
          meson \
            setup builddir \
            -Ddefault_library=shared \
            -Dbuild-object-only=${{ matrix.build_object_only }} \
            \
            -Dpic-enable=${{ matrix.pic_enable }} \
            \
            -Dtest-enable=true \
            -Dtest-pie-enable=true

      - name: Compile
        run: meson compile -C builddir

      - name: Run Tests
        working-directory: .
        run: meson test -C builddir --num-processes 4 --print-errorlogs

  build-options-windows:
    name: Windows-x64 - OBJECT:true
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install Meson & Ninja
        run: pip install meson ninja

      - name: Setup Windows Env
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure
        run: meson setup builddir -Dbuild-object-only=true -Dtest-enable=true

      - name: Compile
        run: meson compile -C builddir

      - name: Run Tests
        working-directory: .
        run: meson test -C builddir --num-processes 4 --print-errorlogs
